import { Component, OnInit } from '@angular/core';

@Component({
  selector: '',  // Generated by app.routes.ts
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
