const mongoose = require('mongoose');  // MongoDb
const { Schema } = mongoose;  // Only need Schema

const PokemonSchema = new Schema ({  // Pokemon Model
  'name': {type: String, required: true, index: { unique: true }},
  'pokedex': {type: Number, required: true},
  'picture': {type: String, required: true},
  'grade': {type: String, required: true},
  'evolution': {type: String, required: true},
  'type': {type: String, required: true},
  'type2': {type: String, required: true},
  'attack': {type: String, required: true},
  'legend': {type: String, required: true},
  'description': {type: String, required: true},
  'family': {type: String, required: true},
  'ability': {type: String, required: true},
  'bability': {type: String, required: true},
  'item': {type: String, required: true},
  'item_picture': {type: String, required: true},
  'item2': {type: String, required: true},
  'item2_picture': {type: String, required: true},
  'zmove': {type: String, required: true},
  'good1': {type: String, required: true},
  'good2': {type: String, required: true},
  'good3': {type: String, required: true},
  'bad1': {type: String, required: true},
  'bad2': {type: String, required: true},
  'bad3': {type: String, required: true},
  'move1': {type: String, required: true},
  'move2': {type: String, required: true},
  'move3': {type: String, required: true},
  'move4': {type: String, required: true},
  'HP': {type: Number, required: true},
  'ATK': {type: Number, required: true},
  'DEF': {type: Number, required: true},
  'SATK': {type: Number, required: true},
  'SDEF': {type: Number, required: true},
  'SPD': {type: Number, required: true},
  'SS': {type: Number, required: true},
  'ef_HP': {type: Number, required: true},
  'ef_ATK': {type: Number, required: true},
  'ef_DEF': {type: Number, required: true},
  'ef_SATK': {type: Number, required: true},
  'ef_SDEF': {type: Number, required: true},
  'ef_SPD': {type: Number, required: true},
  'nature': {type: String, required: true},
  'nature2': {type: String, required: true},
  'info': {type: String, required: true},
  'ready': {type: String, required: true}
});
// Set Pokemon Schema as mongoose Model
module.exports = mongoose.model('Pokemon', PokemonSchema);
// MongoDB will create a Collection 'Pokemon' -> 'pokemons'
