import { Component, OnInit } from '@angular/core';

import { AuthService } from '../../../services/auth.service';  // Auth0 Service
import { TrainerService } from '../../../services/trainer.service';  // Trainer Service


@Component({
  selector: '', // Generated by routes.ts
  templateUrl: './welcome.component.html',
  styleUrls: ['./welcome.component.css']
})
export class WelcomeComponent implements OnInit {

  constructor(private authService: AuthService,
              private trainerService: TrainerService) {}

  ngOnInit() {
    if (this.authService.isAuthenticated()) {  // Only If Logged In with Auth0
      this.authService.getProfile((err, profile) => {  // Get the Profile
      // After We get the Trainer We check it
      this.trainerService.checkTrainer(profile).then(res =>{
      console.log(res);
    })
      });
      }

    }


}
