import { Component, OnInit } from '@angular/core';

import { AuthService } from '../../../services/auth.service';  // Auth0 Service
import { TrainerService } from '../../../services/trainer.service';  // Trainer Service

@Component({
  selector: '', // Generated by app.routes.ts
  templateUrl: './welcome.component.html',
  styleUrls: ['./welcome.component.css']
})
export class WelcomeComponent implements OnInit {

  constructor(private authService: AuthService,
              private trainerService: TrainerService) {}

  ngOnInit() {
  if (this.authService.isAuthenticated()) {  // The User is Authenticated?
      this.authService.getProfile((err, profile) => {  // Get the Profile
      // After We get the Trainer We check it
      this.trainerService.checkTrainer(profile);

      let status = {  // Status Online - Offline We send to Server
        online: true,
        trainerID: this.trainerService.trainerID
      };

        this.trainerService.updateStatus(status).subscribe(res => {});  // Update Status Online
      });
    }

  }


}
